"""Skill Self-Evolution Type Definitions.

This module defines the data structures for tracking skill execution traces
and proposing evolution updates, inspired by Trace2Skill and EvoSkill papers.

Key Concepts:
- Trace: A single skill invocation record (query → rules applied → outcome)
- Proposal: A patch suggestion from analyzing one or more traces
- Validation: Before/after comparison on test cases to gate updates
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ExecutionOutcome(str, Enum):
    """Result of a skill-guided task execution."""
    SUCCESS = "success"          # Task completed successfully, no issues
    PARTIAL = "partial"          # Task completed but with warnings/workarounds
    FAILURE = "failure"          # Task failed, error occurred
    REGRESSION = "regression"    # Previously working feature now broken


@dataclass
class RuleReference:
    """Reference to a specific rule within a skill file.

    Attributes:
        skill_name: Name of the skill (e.g., "dev-process-backend")
        rule_id: Unique identifier for the rule (e.g., "rule_14")
        line_range: Optional line numbers in SKILL.md where rule is defined
    """
    skill_name: str
    rule_id: str
    line_range: tuple[int, int] | None = None  # (start, end)


@dataclass
class SkillEvolutionTrace:
    """A complete trace of a single skill invocation.

    This is the fundamental unit of data for skill self-evolution.
    Each trace captures what happened when a skill was loaded and applied.

    Attributes:
        trace_id: Unique identifier for this trace
        timestamp: Unix timestamp when trace was recorded
        session_id: Associated agent session ID
        user_query: The original user query that triggered skill loading
        skill_name: Which skill was loaded (e.g., "dev-process-backend")
        loaded_rules: List of rule IDs that were active during this invocation
        execution_outcome: Whether the guided task succeeded/failed
        execution_details: Additional context about what happened
        new_rules_discovered: Rules that were added as result of this trace
        user_feedback: Explicit feedback from user (if provided)
        regression_info: If this trace detected a regression, details here
    """
    trace_id: str
    timestamp: float = field(default_factory=time.time)
    session_id: str | None = None
    user_query: str = ""
    skill_name: str = ""
    loaded_rules: list[str] = field(default_factory=list)
    execution_outcome: ExecutionOutcome = ExecutionOutcome.SUCCESS
    execution_details: dict[str, Any] = field(default_factory=dict)
    new_rules_discovered: list[dict] = field(default_factory=list)
    user_feedback: str | None = None
    regression_info: dict[str, Any] | None = None

    def mark_success(self, details: dict[str, Any] | None = None):
        """Mark this trace as successful."""
        self.execution_outcome = ExecutionOutcome.SUCCESS
        if details:
            self.execution_details.update(details)

    def mark_failure(self, error: str, details: dict[str, Any] | None = None):
        """Mark this trace as failed."""
        self.execution_outcome = ExecutionOutcome.FAILURE
        self.execution_details["error"] = error
        if details:
            self.execution_details.update(details)

    def mark_regression(self, affected_rule: str, details: dict[str, Any]):
        """Mark this trace as detecting a regression."""
        self.execution_outcome = ExecutionOutcome.REGRESSION
        self.regression_info = {
            "affected_rule": affected_rule,
            **details
        }


@dataclass
class PatchProposal:
    """A proposed change to a skill's rules.

    Generated by analyzing one or more traces. Similar to a git patch
    but for markdown content.

    Attributes:
        proposal_id: Unique identifier for this proposal
        source_traces: Trace IDs that led to this proposal
        skill_name: Target skill to modify
        operation: Type of change ("add", "modify", "delete", "merge")
        target_rule_id: Which rule to modify (for modify/delete/merge)
        new_content: New rule content (for add/modify)
        rationale: Why this change is proposed
        confidence: Estimated likelihood this change helps (0.0-1.0)
        supporting_evidence: Trace excerpts that support this proposal
    """
    proposal_id: str
    source_traces: list[str]  # trace_ids
    skill_name: str
    operation: str  # "add" | "modify" | "delete" | "merge"
    target_rule_id: str | None = None
    new_content: str | None = None
    rationale: str = ""
    confidence: float = 0.5
    supporting_evidence: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "proposal_id": self.proposal_id,
            "source_traces": self.source_traces,
            "skill_name": self.skill_name,
            "operation": self.operation,
            "target_rule_id": self.target_rule_id,
            "new_content": self.new_content,
            "rationale": self.rationale,
            "confidence": self.confidence,
            "supporting_evidence": self.supporting_evidence,
        }


@dataclass
class MergedProposal:
    """Result of merging multiple PatchProposals.

    After hierarchical merge, conflicting proposals are resolved and
    duplicates removed.

    Attributes:
        merged_proposals: List of non-conflicting proposals ready to apply
        conflicts: List of proposals that couldn't be merged (need human review)
        discarded: Proposals deemed noise/outliers during merge
        merge_rationale: Explanation of how merge was performed
    """
    merged_proposals: list[PatchProposal] = field(default_factory=list)
    conflicts: list[tuple[PatchProposal, PatchProposal, str]] = field(default_factory=list)
    discarded: list[PatchProposal] = field(default_factory=list)
    merge_rationale: str = ""


@dataclass
class TestCase:
    """A test case for validating skill changes.

    Used by the Validation Gate to ensure proposed changes actually help.

    Attributes:
        test_id: Unique identifier
        description: What this test validates
        input_query: The query to feed to agent
        expected_behavior: What should happen (text description)
        success_criteria: Callable or string to check if test passed
        tags: Categories this test belongs to
    """
    test_id: str
    description: str
    input_query: str
    expected_behavior: str
    success_criteria: str | callable  # e.g., "no_error" or lambda result: "rule_14" in result
    tags: list[str] = field(default_factory=list)


@dataclass
class ValidationResult:
    """Result of validating a proposed skill change.

    Attributes:
        proposal_id: Which proposal was tested
        score_delta: Performance change (-1.0 to +1.0)
        passed: Whether validation threshold was met
        test_results: Per-test-case results
        failed_cases: Test cases that failed (for feedback loop)
        recommendation: "accept" | "reject" | "needs_review"
    """
    proposal_id: str
    score_delta: float
    passed: bool
    test_results: list[tuple[str, bool, str]]  # (test_id, passed, message)
    failed_cases: list[str] = field(default_factory=list)
    recommendation: str = "reject"  # "accept" | "reject" | "needs_review"

    def __post_init__(self):
        if self.passed and self.score_delta >= 0.05:
            self.recommendation = "accept"
        elif self.score_delta < -0.05:
            self.recommendation = "reject"
        else:
            self.recommendation = "needs_review"


@dataclass
class EvolutionSummary:
    """Summary of a complete evolution cycle.

    Generated after a batch of traces has been analyzed, proposals merged,
    and validations completed.

    Attributes:
        cycle_id: Unique identifier for this evolution cycle
        timestamp: When cycle completed
        traces_analyzed: Number of traces processed
        proposals_generated: Number of unique proposals
        proposals_accepted: Number that passed validation
        proposals_rejected: Number that failed validation
        skills_updated: Which skills were actually modified
        performance_impact: Aggregate impact across all tests
    """
    cycle_id: str
    timestamp: float = field(default_factory=time.time)
    traces_analyzed: int = 0
    proposals_generated: int = 0
    proposals_accepted: int = 0
    proposals_rejected: int = 0
    skills_updated: list[str] = field(default_factory=list)
    performance_impact: dict[str, float] = field(default_factory=dict)  # skill_name → score_delta
